### ISSUE TITLE
Extension Not Working

### ISSUE THREAD

**Issue by Invisible40** [ryanpcmcquen/side_by_side_gdocs#1]
The extension will move the documents, however they will not put them literally next to each other. So, I still have to scroll down to see the second page of a Google Doc, however instead the second page is to the right instead of the middle.

**Comment by ryanpcmcquen** [comment]
What is your screen resolution/will you send me a screenshot? I've tested it on a few resolutions here and it works fine.

**Comment by ryanpcmcquen** [comment]
So I did a little experimenting, seems that `1632` (or greater) is the required width for this to work.

Unfortunately, even zooming down does not work, because Google does some voodoo magic on the zoom settings. I'll see if I can find a workaround, but nothing is seeming obvious right off the bat ... if anyone has an idea I would love to make this work. :smile_cat:

`1631`:
![two_pages_will_not_fit_at_1631](https://cloud.githubusercontent.com/assets/772937/18537432/453e9c40-7aba-11e6-9869-86d98ff0127b.png)

`1632`:
![two_pages_will_fit_at_1632](https://cloud.githubusercontent.com/assets/772937/18537437/4c5b87ea-7aba-11e6-8ce7-5531cc12a64d.png)

I've added it to the known issues on the [README](https://github.com/ryanpcmcquen/side_by_side_gdocs/blob/master/README.md):
https://github.com/ryanpcmcquen/side_by_side_gdocs/commit/2e4c03d6e42ea143fd61c481f7467056215e8b19

**Comment by Invisible40** [comment]
Hi there,

It seems like you're right. I'm using a 1366x768 resolution. Hopefully it'll get fixed, thanks!

**Comment by ryanpcmcquen** [comment]
If you want to keep the extension around for when you _are_ on a bigger screen, I have changed it so that the toggle button only loads on suitable resolutions.

Thanks for the report!

**Comment by saiplanner** [comment]
This extension is not there in the chrome web store. 
How do I install this?
